# Site Details
site-name: "Project Name"

# Application theme:
theme:
  - bgcolor: "#2e2f3e"
  - primary: "teal"

# Navigation tree:
nav:
  - Home: "index.py"
  - Contact: "contact.py"
  - Docs: "docs.py"
